Deletes `waitForLoading()` from `PoetryRobots`.
* When I merged `ray/ui-update` into `main`, I broke `renderPassCounterComplexNoInitializingState` and `renderPassCounterComplexWithInitializingState`.
* This is because I deleted the l`oading_dialog` id that LoadingDialogSelector` looks for
* I deleted that because I deleted `LoaderContainer`, now redundant with `BodyAndModalsContainer`
* It once said:

```kotlin
    viewConstructor = { initialRendering, initialEnv, contextForNewView, _ ->
      LoaderContainer(contextForNewView).apply {
        id = R.id.loading_dialog
        layoutParams = ViewGroup.LayoutParams(
          ViewGroup.LayoutParams.MATCH_PARENT,
          ViewGroup.LayoutParams.MATCH_PARENT
        )
        bindShowRendering(initialRendering, initialEnv, ::update)
      }
```
* But that id would always be visible, as it applied to the LoaderContainer frame itself, not the loading dialog it may or may not be showing.

So I'm deleting the pointless `waitForLoading()` function, and now everything passes.

Also note a change to one of the benchmark baselines:

```
java.lang.AssertionError: Congrats! You have improved the the number of Render Passes (lower better) by 4 (6.56%) in the 'Raven navigation with initializing state scenario'! Please update the expected value for your config. The value is now 57.
at org.junit.Assert.fail(Assert.java:89)connectedDebugAndroidTest
```

```
  java.lang.AssertionError: Hmmm. The the fresh rendering ratio (higher better) has improved nullin the 'Raven navigation with initializing state scenario', but only because the scenario has changed, impacting expectation but not for the better. The value is now (ratio: 0.119; fresh renderings: 83; stale renderings: 615). Please update the test.
```